### ISSUE TITLE
El index.html no corresponde al proyecto

### ISSUE THREAD

**Issue by danicricco** [jokoframework/security#11]
El archivo que encuentra en  src/main/resources/public/index.html no corresponde al proyecto. Esto resulta muy inconveniente puesto que al ser incluido en un proyecto que no posee "index", es la página que se termina mostrando.

**Comment by danicricco** [comment]
Se soluciona en https://github.com/jokoframework/security/pull/17

**Comment by roskoff** [comment]
También se agregó como bugfix de la versión 0.1.8 vía #21. Considero que este issue ya se puede cerrar.
