### ISSUE TITLE
La tabla audit parece no tener utilidad. Evaluar deprecarla

### ISSUE THREAD

**Issue by danicricco** [jokoframework/security#13]
La tabla audit parece no tener utilidad alguna. Para emitir la opinión me paso en lo siguiente:

1) Audit solo se llena desde un Controller en particular (AuditSessionController)
Es decir, el cliente tiene que explícitamente llamar a este URL para ser auditado. Sin comprender el caso de uso que motivó a su creación, parece no tener sentido. 

Si se desea auditar la emisión de tokens, esto no debe ser voluntario. Un cliente podría llamar, obtener un token y decidir no llamar al método de auditoría. La auditoría debería de darse como consecuencia de que se emitió un token.

2) La información que se almacena en audit ya está en la tabla tokens.
La información que se está pretendiendo guardar desde "audit" ya se encuentra en la tabla "tokens"

## Propuesta
Mi propuesta concreta es eliminar la tabla Audit y los objetos que se construyen encima de ella.

**Comment by danicricco** [comment]
En lugar de deprecar una idea propuesta por bsandoval es que se use la misma estructura para que funcione la auditoria a medida que llegan los pedidos

**Comment by alefq** [comment]
Tenemos ejemplo de auditoría con Envers de Hibernate. Veo de orquestar esto para realizar con ejemplos concretos dentro del backend starter kit.
