### ISSUE TITLE
Persistir datos del mapa custom en base de datos

### ISSUE THREAD

**Issue by alefq** [jokoframework/security#3]
Actualmente Joko Security recibe un JSON para la autenticación del formato:

```
{
  "username":"sodep",
  "password":"PONER_AQUI_EL_PASSWORD",
  "custom": {
    "codigoEmpresa":123,
    "codigoSucursal": 2,
    "codigoCaja":982341
  }
}
```
pero el mapa `custom` no es persistido en la base de datos. 
El objetivo del ticket es que esta información sea almacenada en una columna y pueda ser recuperado en una instancia cualquiera de un token.

**Comment by danicricco** [comment]
que pasa si dentro de custom hay datos sensibles ? no deberían estos de guardarse encriptados ?

que se almacene en la BD no tiene relación directa con que este en el token. Es decir, puede estar en la BD en una columna y no formar parte del token, o puede formar parte del token sin estar en una columna por separado.

Capaz si aclaramos mejor la intención podemos debatir su utilidad.

**Comment by danicricco** [comment]
@alefq crees que sigue siendo válido este ticket ?

**Comment by alefq** [comment]
La motivación detrás estaba por poder obtener información de auditoría, por ej. saber de dónde provenía qué sesión (token), pero concuerdo en que quizá es muy particular para cierto tipo de apps. 
Cierro el ticket, si surge de nuevo la necesidad crearemos un nuevo ticket.
