### ISSUE TITLE
Persistir información de los request originados por cada token/sesión

### ISSUE THREAD

**Issue by alefq** [jokoframework/security#4]
Un ingreso/login exitoso, genera un `refresh_token` que luego se utiliza para ralizar los demás requests REST. 
El objetivo de este ticket, es almacenar en un esquema tipo `master/detail` todos los requests generados por ese `refresh_token`, con  informaciones de auditoría obtenidas del request
1. Nro. de IP que genera el request
2. Nro. de IP de la cabecera `X-Forwarded-For` (si existe)
3. User Agent

**Comment by danicricco** [comment]
Cual es la motivación de esto ? Si en cada request guardamos va a ser muy intenso en datos y una de las ideas de los access token firmados con JWT es que no tengas que tocar la BD para verificar su autenticidad. 

Deberíamos de agregar algun parámetro para activar/desactivar esta característica ?

**Comment by alefq** [comment]
Cierro el ticket, ya que el objetivo tenía una aplicación muy específica (con fines de tracking de uso potencialmente indebido) para un proyecto y no se presentó la necesidad de nuevo en otro caso.
