### ISSUE TITLE
La clase Application.java tiene configuración no necesaria para librerías empaquetadas como JAR

### ISSUE THREAD

**Issue by rodrigojv** [jokoframework/security#5]
En concreto, [la documentación de Spring Boot](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-a-deployable-war-file) menciona algunos requisitos que debe tener el `Application.java` para que un proyecto Spring Boot sea deployable como war.

Joko security no necesita cumplir esos requisitos, como por ejemplo extender de `SpringBootServletInitializer`.

Se debería modificar y quitar estas configuraciones, teniendo en cuenta que el objetivo de este proyecto es poder ser utilizado como librería empaquetada como JAR en otros proyectos.

Problemas similares pueden encontrarse aquí: https://github.com/spring-projects/spring-boot/issues/5033

**Comment by danicricco** [comment]
Una idea era que pueda efectivamente ser deployado como un componente separado. De hecho en el README dice esto al comienzo. En este caso, sería un componente Web.

Para resolver esto lo que podemos hacer es:
* Mantener el proyecto joko-security con el espíritu de ser una librerría
* Eventualmente crear otro que sea un proyecto emisor de tokens (como AWS cognito).

Dejo abierto el ticket para realizar lo que pide el requerimiento original y mantener a joko-security como una librería.

**Comment by bsandoval** [comment]
Resuelto en #17 . Se mantiene el proyecto joko-security como librería (JAR)
