### ISSUE TITLE
Publicar la librería como github package

### ISSUE THREAD

**Issue by alefq** [jokoframework/security#57]

**Comment by Dyuko** [comment]
Listo.

**Comment by alefq** [comment]
@Dyuko  por favor agregá alguna referencia a los pasos a seguir para publicar como github package, si es que hay documentación directa de Github; o una entrada en la Wiki de Joko en caso de que hayas consultado varias fuentes.

**Comment by Dyuko** [comment]
Para publicar como github package se siguió la documentación directa de Github:
https://docs.github.com/es/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages

Por otra parte, al momento de publicar el paquete con `mvn deploy` hubo errores relacionados con los plugins de maven, por lo que fue necesario establecer la versión mínima de maven requerida y actualizar las versiones de los plugins de acuerdo a la versión maven, como se muestra en #60

**Comment by alefq** [comment]
:muscle:
